### ISSUE TITLE
报错：TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by pengej** [hzsrc/webpack-iconfont-plugin-nodejs#31]
npm run serve的时候，更新或提交SVN版本时，偶发地会报这个错误，并且导致npm服务进程退出。

```
TypeError: Cannot read property 'length' of null
    at FSWatcher.<anonymous> (C:\Projects\app\node_modules\webpack-iconfont-plugin-nodejs\src\index.js:66:34)
    at FSWatcher.emit (events.js:375:28)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:186:12)
````
可能是如下代码没有判断filename为null的情况
```js
fs.watch(dir, (event, filename) => {
    if (filename.length > 4 && filename.slice(-4) === '.svg') {
        comileDebounce()
    }
});
```

这个问答展示了出现问题的原因：[fs-watch-is-returning-null-for-the-file-name](https://stackoverflow.com/questions/9629307/fs-watch-is-returning-null-for-the-file-name)

**Comment by hzsrc** [comment]
已修复
